### PR TITLE
Add vector tile endpoint

### PR DESCRIPTION
**Pull request by chriswhong**
This PR adds a simple vector tile endpoint and refactors the express server:

- Adds `/tiles/initialize` endpoint, pass in a SQL query using query param `q`, returns JSON object with `tiles` (vector tile template) and `bounds` (bbox for the query, useful for calling fitbounds )

- Adds `/tiles/:tileId/:z/:x/:y.mvt` endpoint, serves vector tiles for the query stored in `tileId`

- Adds eslint, cleans up all eslint errors and warnings.

- Adds `routes` directory for express route handling

- Adds `queries` directory to store .sql files for use with pg-promise

- Upgrades node dependencies

### CODE REVIEW

**Comment by brianbancroft** [comment]
One problem observed: 

`error: function st_asmvtgeom(geometry, geometry, integer, integer, boolean) does not exist` fires back from every subsequent tile query from uri's such as `http://localhost:4000/tiles/r3zhpB7Ht/9/148/184.mvt`

**Comment by chriswhong** [comment]
Oh you are not using the latest postgis, st_asmvtgeom is new in 2.4

**Comment by brianbancroft** [comment]
That was actually what happened. Thanks for the assistance there. 

I still haven't been able to get that part to work at my database level, but I'm noticing that when I try to reload the query that the tile source and layer fail to refresh because we're trying to add multiple layers and sources of the same name. The easiest way to deal with that may be the following in the `Map` component: 


```js
  removeLayers() {
    if (
      this.map
        .getStyle()
        .layers.map(i => i.id)
        .includes('postgis-preview-tiles')
    ) {
      this.map.removeLayer('postgis-preview-tiles');
      this.map.removeSource('postgis-preview-tiles');
    }
  }
```

**Comment by chriswhong** [comment]
With work from myself and @brianbancroft, this PR refactors the frontend to:
- Use react components (Uses script tags in index.html to import JSX components + babel)
- Use mapboxGL
- Adds a vector tile endpoint that can be used in the future.  The default `/sql` endpoint is still default, but now serves geojson instead of topojson.

These are the core improvements for release 0.2.0, we still need to improve the table view, add UI for using vector tiles, etc.

**Pull request merged**
